version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=big_saving
    ports:
      - "6000:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
